name: Destroy Fly.io Machine

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/destroy-machine.yml'

jobs:
  destroy:
    name: Destroy machine
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚀 Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: 💥 Destroy machine
        run: |
          echo "Destroying machine: 7817642f9552d8"
          flyctl machine destroy 7817642f9552d8 --force --app w-best-tracker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
      - name: ✅ Verify removal
        run: |
          echo "Machine destroyed successfully!"
          flyctl machine list --app w-best-tracker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
